const myElements = [
    {
        titleH1: "Création de la WNBA",
        subtitle: "Sous-titre",
        text: "La Women's National Basketball Association (WNBA) a été fondée le 24 avril 1996 comme une ligue de basket-ball professionnel féminin aux États-Unis.",
        year: 1996,
        date: "1996-04-24",
        valueType: "A",
        personProfile: "Pierre",
        button: true,
    },
    {
        titleH1: "Première saison de la WNBA",
        subtitle: "Sous-titre2",
        text: "La première saison de la WNBA a eu lieu en 1997, avec huit équipes participant à la compétition.",
        year: 1997,
        date: "1997-06-21",
        valueType: "B",
        personProfile: "Arthur",
        button: false,
    },
    {
        titleH1: "Ouverture de la saison 2020 de la WNBA",
        subtitle: "Sous-titre3",
        text: "La saison 2020 de la WNBA a débuté le 25 juillet 2020 avec un match entre le Seattle Storm et le New York Liberty.",
        year: 2020,
        date: "2020-07-25",
        valueType: "C",
        personProfile: "Moïse",
        button: true,
    },
    {
        titleH1: "Championnat de la WNBA 2001",
        subtitle: "Sous-titre4",
        text: "Le championnat de la WNBA 2001 a été remporté par les Los Angeles Sparks après avoir battu les Charlotte Sting lors des finales.",
        year: 2001,
        date: "2001-10-01",
        valueType: "D",
        personProfile: "Grey",
        button: false,
    },
    {
        titleH1: "Retraite de Lisa Leslie",
        subtitle: "Sous-titre5",
        text: "Lisa Leslie, l'une des plus grandes joueuses de la WNBA, a annoncé sa retraite le 21 février 2009 après une carrière exceptionnelle.",
        year: 2009,
        date: "2009-02-21",
        valueType: "A",
        personProfile: "John",
        button: true,
    },
    {
        titleH1: "Draft WNBA 2018",
        subtitle: "Sous-titre6",
        text: "La draft WNBA 2018 a été marquée par la sélection de A'ja Wilson en première position par les Las Vegas Aces.",
        year: 2018,
        date: "2018-04-12",
        valueType: "B",
        personProfile: "Kevin Keutin",
        button: false,
    },
    {
        titleH1: "Finales de la WNBA 2016",
        subtitle: "Sous-titre7",
        text: "Les Finales de la WNBA 2016 ont vu les Los Angeles Sparks battre le Minnesota Lynx pour remporter le championnat.",
        year: 2016,
        date: "1990-10-20",
        valueType: "C",
        personProfile: "Mathilde",
        button: true,
    },
    {
        titleH1: "Changement de logo de la WNBA",
        text: "En avril 2019, la WNBA a dévoilé un nouveau logo mettant en avant l'engagement envers l'égalité et l'émancipation des femmes.",
        year: 2019,
        date: "2019-04-01",
        valueType: "D",
        personProfile: "Yvan",
        button: false,
    },
    {
        titleH1: "MVP de la saison 2000",
        text: "Sheryl Swoopes a été nommée MVP de la saison régulière WNBA 2000, honorant sa performance exceptionnelle.",
        year: 2000,
        date: "2000-09-15",
        valueType: "A",
        personProfile: "Copp",
        button: true,
    },
    {
        titleH1: "Expansion de la WNBA en 1999",
        subtitle: "Sous-titre9",
        text: "En 1999, la WNBA a accueilli quatre nouvelles équipes, portant le nombre total d'équipes à douze.",
        year: 1999,
        date: "1999-01-01",
        valueType: "B",
        personProfile: "Mathilde",
        button: false,
    },
    {
        titleH1: "Record de points de Diana Taurasi",
        text: "Le 17 juin 2017, Diana Taurasi a battu le record de points en carrière de la WNBA, établissant un nouveau record avec 7 494 points.",
        year: 2017,
        date: "2017-06-17",
        valueType: "C",
        personProfile: "Moïse",
        button: true,
    },
    {
        titleH1: "Expansion de la WNBA en 2000",
        subtitle: "Sous-titre23",
        text: "En 2000, la WNBA a ajouté deux nouvelles équipes, le Miami Sol et le Portland Fire, portant le nombre total d'équipes à seize.",
        year: 2000,
        date: "2000-01-01",
        valueType: "D",
        personProfile: "John",
        button: false,
    },
    {
        titleH1: "Rebaptisation des Detroit Shock",
        text: "En 2009, les Detroit Shock ont été rebaptisées Tulsa Shock après avoir été vendues à un nouveau propriétaire.",
        year: 2009,
        date: "2009-01-01",
        valueType: "A",
        personProfile: "Arthur",
        button: true,
    },
    {
        titleH1: "Élargissement des audiences de la WNBA",
        text: "Au fil des années, la WNBA a connu une croissance significative de son audience, attirant de plus en plus de spectateurs et de supporteurs.",
        year: 2025,
        date: "2025-01-01",
        valueType: "B",
        personProfile: "Kevin Keutin",
        button: false,
    },
    {
        titleH1: "Finales de la WNBA 2024",
        text: "Les Finales de la WNBA 2024 ont vu les Chicago Sky remporter leur premier championnat en battant les Phoenix Mercury.",
        year: 2024,
        date: "2024-09-22",
        valueType: "C",
        personProfile: "Mathilde",
        button: true,
    },
    {
        titleH1: "Expansion de la WNBA en 2002",
        text: "En 2002, la WNBA a ajouté deux nouvelles équipes, le Charlotte Sting et le Miami Sol, portant le nombre total d'équipes à seize.",
        year: 2002,
        date: "2002-01-01",
        valueType: "D",
        personProfile: "Yvan",
        button: false,
    },
    {
        titleH1: "Changement de nom des Minnesota Lynx",
        text: "En 2006, les Minnesota Lynx ont changé de nom pour devenir les Minnesota Timberwolves, alignant ainsi le nom de l'équipe avec celui de l'équipe de la NBA dans la même ville.",
        year: 2006,
        date: "1992-01-01",
        valueType: "A",
        personProfile: "Copp",
        button: true,
    },
    {
        titleH1: "Journée d'ouverture de la WNBA 2005",
        text: "La saison 2005 de la WNBA a débuté le 21 mai 2005 avec plusieurs matchs d'ouverture.",
        year: 2005,
        date: "2005-05-21",
        valueType: "B",
        personProfile: "John",
        button: false,
    },
    {
        titleH1: "Titre de MVP de la saison 2019",
        text: "Elena Delle Donne a été nommée MVP de la saison WNBA 2019 pour ses performances exceptionnelles tout au long de la saison.",
        year: 2019,
        date: "2019-09-19",
        valueType: "C",
        personProfile: "Grey",
        button: true,
    },
    {
        titleH1: "Expansion de la WNBA en 1998",
        text: "En 1998, la WNBA a accueilli deux nouvelles équipes, le Washington Mystics et les Detroit Shock, portant le nombre total d'équipes à dix.",
        year: 1998,
        date: "1994-01-01",
        valueType: "D",
        personProfile: "Mathilde",
        button: false,
    },
];

export default myElements;
